### ISSUE TITLE
when i run the 'features = data_utils.read_gen_sparse(feat_fname)' ,i got some wrong. 

### ISSUE THREAD

**Issue by LLLLLLoki** [Extreme-classification/siamesexml#10]
D:\soft\anaconda\envs\nlp_pytorch\python.exe E:/code/MLTC/siamesexml-master/siamesexml/test_code.py
C:\Users\xjliu16\AppData\Roaming\Python\Python37\site-packages\xclib-0.97-py3.7-win-amd64.egg\xclib\data\data_utils.py:263: UserWarning: Header mis-match from inferred shape!
  warnings.warn("Header mis-match from inferred shape!")
Traceback (most recent call last):
  File "E:/code/MLTC/siamesexml-master/siamesexml/test_code.py", line 32, in <module>
    features = data_utils.read_gen_sparse(feat_fname)
  File "C:\Users\xjliu16\AppData\Roaming\Python\Python37\site-packages\xclib-0.97-py3.7-win-amd64.egg\xclib\data\data_utils.py", line 154, in read_gen_sparse
    header, force_header, safe_read)
  File "C:\Users\xjliu16\AppData\Roaming\Python\Python37\site-packages\xclib-0.97-py3.7-win-amd64.egg\xclib\data\data_utils.py", line 269, in read_sparse_file
    assert shape[1] <= _header_shape[1], "num_cols_inferred > num_cols_header"
AssertionError: num_cols_inferred > num_cols_header
shape: (147402, 171794396884325)
_header_shape: (294805, 40000)

Process finished with exit code 1
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
I don't quite understand the structure of ‘LF-AmazonTitles-131K’ data set, and I don't know what to do about this error. Can you help me to check the following, thanks

**Comment by LLLLLLoki** [comment]
In  LF-AmazonTitles-131K dataset ,how to find the original text from the trn_X_Xf.txt or tst_X_Xf.txt

**Comment by LLLLLLoki** [comment]
When 
data: array('d', [3.69003701210022, 3.897750854492188, 9.289081573486328, 5.22029447555542, 6.573582649230957, ....])
ind: array('l', [16, 119, 285, 304, 930, 1771, 2101, 2285, 18336, 16, 66, 93, 112, 2421, 4579, 5460, 6216, 7878, 8551, 8681, ....])
indptr: array('l', [0, 9, 22, 27, 34, 54, 62, 64, 77, 78, 81, 85, 90, 99, 106, 111, 123, 136, 144, 149, 167, 172, 176, 186])

 become indeces: [   511101108240   1305670058269   7606387082146   9814000273461
     68719495072    399431958594  10398115823728  23450521440739
  33835752364104  37284611105127 161323266616337   1752346656873...]
indptr: [ 38654705664 115964117014 231928234018 274877907006 335007449165
 365072220241 425201762394 476741369962 584115552379 639950127248
 738734375079 798863917232]
data: [ 3.690037   3.8977509  9.289082   5.2202945  6.5735826  7.332547
  8.141828   7.6357613 10.629706   3.690037   7.1650867  7.763432...]
 after passing np.frombuffer

**Comment by LLLLLLoki** [comment]
when i change the code the problem is OK
def _read_file_safe(f, dtype, zero_based, query_id,
                    offset=0, length=-1, header=True):
     ......
    data = np.frombuffer(data, actual_dtype)
    indices = np.frombuffer(ind, np.int32)# np.int64-->np.int32
    indptr = np.frombuffer(indptr, dtype=np.int32)   # never empty
    query = np.frombuffer(query, np.int32)
    data = np.asarray(data, dtype=dtype)

**Comment by kunaldahiya** [comment]
This is a Windows specific issue. You can use 32 bit or follow the solution [here](https://github.com/kunaldahiya/pyxclib/issues/23#issuecomment-1198409035).

**Comment by LLLLLLoki** [comment]
> D:\soft\anaconda\envs\nlp_pytorch\python.exe E:/code/MLTC/siamesexml-master/siamesexml/test_code.py C:\Users\xjliu16\AppData\Roaming\Python\Python37\site-packages\xclib-0.97-py3.7-win-amd64.egg\xclib\data\data_utils.py:263: UserWarning: Header mis-match from inferred shape! warnings.warn("Header mis-match from inferred shape!") Traceback (most recent call last): File "E:/code/MLTC/siamesexml-master/siamesexml/test_code.py", line 32, in features = data_utils.read_gen_sparse(feat_fname) File "C:\Users\xjliu16\AppData\Roaming\Python\Python37\site-packages\xclib-0.97-py3.7-win-amd64.egg\xclib\data\data_utils.py", line 154, in read_gen_sparse header, force_header, safe_read) File "C:\Users\xjliu16\AppData\Roaming\Python\Python37\site-packages\xclib-0.97-py3.7-win-amd64.egg\xclib\data\data_utils.py", line 269, in read_sparse_file assert shape[1] <= _header_shape[1], "num_cols_inferred > num_cols_header" AssertionError: num_cols_inferred > num_cols_header shape: (147402, 171794396884325) _header_shape: (294805, 40000)
> 
> Process finished with exit code 1 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ I don't quite understand the structure of ‘LF-AmazonTitles-131K’ data set, and I don't know what to do about this error. Can you help me to check the following, thanks
