### ISSUE TITLE
Creating the dataset from raw file

### ISSUE THREAD

**Issue by doobybug** [Extreme-classification/siamesexml#11]
I have downloaded the raw files and these contain lbl.json, trn.json, tst.json, filter_labels_test.txt, filter_labels_train.txt

What script was used to transfer these raw json files to the bow version? Is it some script in the pyxclib library?

**Comment by kunaldahiya** [comment]
Hi

The raw data can be accessed using the function available [here](https://github.com/kunaldahiya/pyxclib/blob/e554bb6c6426bf38d786d14e8e02830384e26f2c/xclib/data/data_utils.py#L358). The text (title or title + content) was tokenized using `wordpiece' tokenizer followed by tf-idf feature creation step.
