### ISSUE TITLE
Dataset generation

### ISSUE THREAD

**Issue by mminici** [Extreme-classification/siamesexml#14]
Hi,
For research purposes I am trying to replicate your work and then apply it to a custom dataset.

My issue is that I don't know how to create the file `lbl_X_Xf.txt`.

1. I downloaded the `LF-AmazonTitles-131K` from http://manikvarma.org/downloads/XC/XMLRepository.html
2. I converted `train.txt` and `test.txt` using the script you provided.
3. **I don't know how to create `lbl_X_Xf.txt`**

What I tried so far and didn't work:

- `perl convert_format.pl ${DATA_DIR}/LF-AmazonTitles-131K/filter_labels_train.txt ./data/LF-AmazonTitles-131K/lbl_X_Xf.txt`
- `perl convert_format.pl ${DATA_DIR}/LF-AmazonTitles-131K/label_raw_ids.txt ./data/LF-AmazonTitles-131K/lbl_X_Xf.txt`

Could you please guide me through generating the file `lbl_X_Xf.txt`?

**Comment by anshumitts** [comment]
Hi, You are given Yf.txt in every LF dataset which is label_X_Xf.txt for SiameseXML On 6 Jun 2023 19:48, Marco Minici ***@***.***> wrote:
Hi,
For research purposes I am trying to replicate your work and then apply it to a custom dataset.
My issue is that I don't know how to create the file lbl_X_Xf.txt.
I downloaded the LF-AmazonTitles-131K from http://manikvarma.org/downloads/XC/XMLRepository.htmlI converted train.txt and test.txt using the script you provided
3. I don't know how to create lbl_X_Xf.txt
What I tried so far and didn't work:
perl convert_format.pl ./data/LF-AmazonTitles-131K/filter_labels_train.txt ./data/LF-AmazonTitles-131K/lbl_X_Xf.txtperl convert_format.pl ./data/LF-AmazonTitles-131K/label_raw_ids.txt ./data/LF-AmazonTitles-131K/lbl_X_Xf.txt
Could you please guide me through generating the file lbl_X_Xf.txt?
