### ISSUE TITLE
Recall @ K actually computes full recall ?

### ISSUE THREAD

**Issue by MichalMalyska** [Extreme-classification/siamesexml#2]
https://github.com/Extreme-classification/siamesexml/blob/73bf3ca656d16b9fe53674b3c373eae80a08f93a/misc/sim_in_shortlists.py#L29

**Comment by kunaldahiya** [comment]
Hi,

Yes, this function computes recall till k - can be useful while analyzing things.

**Comment by MichalMalyska** [comment]
What I mean to say is, the parameter k is used nowhere in the code that is not commented out.

**Comment by drei34** [comment]
@kunaldahiya Yes this does seem like an error in this code ... I can push a fix if you need help on this and the other bug I asked about. Assuming this and that one are true bugs.

**Comment by kunaldahiya** [comment]
This code snippet is meant to just analyze things - it is not integral to the main pipeline. recall@k is correctly defined [here](https://github.com/kunaldahiya/pyxclib/blob/608991d500047096ce8a0a3c6b0baabcef5ab3c8/xclib/evaluation/xc_metrics.py#L397).

**Comment by drei34** [comment]
Got it. But it seems it does not use k yet k is a parameter, so I think that's the confusion ... Thank you for the link.

**Comment by kunaldahiya** [comment]
Apologies for the confusion. It was an old code that was not used in the main pipeline - so I let it be.
