### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by hdm30** [Extreme-classification/siamesexml#4]
Hi,

I'm a little bit confused with the embeddings part. In the article, the authors refer to TF-IDF features, while in github repo I realised that fasttext embedding is used as well but I can't understand in which step of the algorithm. Can I have further explanations please?

Many thanks,

**Comment by kunaldahiya** [comment]
Hi,

The encoder compute embeddings as weighted combination of token embeddings - here weights are tf-idf values and token embeddings are learned during training.

We note that initializing the token embeddings with fasttext yields better performance than random initialization. Hence, we use fasttext for initialization in the beginning of training.
