### ISSUE TITLE
OVA classifiers using only refinement vectors not label projection?

### ISSUE THREAD

**Issue by DiegoOrtego** [Extreme-classification/siamesexml#5]
Hi Kunal,

Many thanks for sharing the code of SiameseXML. Hope you can help me with one doubt. While debugging the code in the OVA classifiers training, I can't see where the re-parametrization of the classifiers is happening. As far as I can see, in the classifier forward it's happening the following (forward snapshot in the image below):

1) Embed are the data point embeddings (after the projection with the residual block) that are L2 normalized in line 209
2) The refinement vectors are a embedding matrix and 500 of them are extracted using the shortlist. This happens in line 211, and refinement vectors are stored in short_weigths.
3) The refinement vectors are L2 normalized in line 215.
4) L2 normalized refinement vectors are used as classifiers in the matrix multiplication of Embed and the refinement vectors in line 216.

Therefore, refinement vectors are directly used as classifier vectors (i.e. as in a standard linear layer).
In the paper, wl classifiers are defined as:
    wl = norm(projection(z) + refinement vector)
However, in the code what I see is:
    wl = norm(refinement vector)

Am I missing something?

Thanks in advance!

![image](https://user-images.githubusercontent.com/24732433/190587889-b292c0ec-2e61-4dfc-9a1f-36fde77e28be.png)

**Comment by kunaldahiya** [comment]
Hi

Thanks for checking out the code. The classifiers are initialized with the label embeddings (~re-parametrization) as shown below:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/18436752/191070498-3661a5c4-2d55-4aec-9077-fdd131ba801d.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/18436752/191070066-9c980577-2bd4-4065-856a-729b0bab3d7c.png">

**Comment by DiegoOrtego** [comment]
Many thanks Kunal! I was missing something ;)
