### ISSUE TITLE
Questions related to tokenization and R^V - are you mixing Bert Tokens and FastText embeddings?

### ISSUE THREAD

**Issue by drei34** [Extreme-classification/siamesexml#6]
Hello,

As I understand it, the model need to tokenize text to get the dimension V and then for each token we need its fastText embedding. Some questions:

1) For the sample data set LF-AmazonTitles-131K is the BERT tokenizer used? It seems so, as tokens look like '##abcd' which is the same format and also as BERT. If this is the case, is it wrong to mix fastText embeddings with these? For example, tokens in fastText do not look like '##ab', they look like 'ab' or '<ab' so to get the embedding for '##ab' you'd need to (at a high level) average (2*embedding('#') + embedding('ab')) / 3 or something like this but '##ab' is not a word, it's an artificial token so the meaning of '##ab' is lost if we do this?

2) For inference, how do you make sure that any new query can be expressed in R^V? Do you basically need to make sure that all uni-grams 'a', '$', etc are in the token space V?

Thank you!

**Comment by kunaldahiya** [comment]
Hi, 

Thanks for checking out. Here are the responses:
1. We tried out both things - standard tokenizers and BERT tokenizers. The BERT tokenizer works well (at least for us) even when we use FastText embeddings. The disconnect does exist - if someone can come up with a better initialization, the performance may improve further.
2. We do not consider new tokens, i.e., if there is a new token at inference time, we simply ignore it. This is clearly suboptimal but incorporating new tokens may require some tangential work.

Please let me know if something is still unclear.

**Comment by drei34** [comment]
Hey @kunaldahiya another question - where is the supplementary materials as the paper discussed? I don't think the links work ...
