### ISSUE TITLE
filter_labels_text.txt and filter_labels_train.txt files ... What are they and how do you get them?

### ISSUE THREAD

**Issue by drei34** [Extreme-classification/siamesexml#7]
Hi,

I see that when you run SiameseXML if you set validate = true in the config these are used. How are these generated? Can you add this to the README since there is no mention of these files, but they seem important. Also, what is the purpose of these files?Thank you!

**Comment by kunaldahiya** [comment]
Hi,

Documents and labels can be from the same space in some datasets such as LF-AmazonTitles-131K. So, a document can/should be relevant to itself (as it can appear as a label as well). 

These filter files are meant to ensure that the model is neither penalized nor rewarded for making such predictions. Please use an empty file if your dataset doesn't have any such issue. I'll add it to readme (Thanks for the suggestion!). See [Reciprocal-pair Removal section](http://manikvarma.org/downloads/XC/XMLRepository.html) for more details.

**Comment by drei34** [comment]
Thank you! One question I have because I don't quite understand: "Documents and labels can be from the same space in some datasets such as LF-AmazonTitles-131K. So, a document can/should be relevant to itself (as it can appear as a label as well)." Do you mean that a query (x) can be a title (z), for example, and this file filters out such things? Is that the use case? I don't see why that's actually an issue but just trying to understand ...

**Comment by kunaldahiya** [comment]
Yes. This situation can appear in product-to-product datasets among others. Please note that it can be trivial for some algorithms to make such predictions. The filter file ensures that an algorithm is neither rewarded, nor penalized for such cases.
