### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by drei34** [Extreme-classification/siamesexml#8]
Hi,

I think there is a bug in the line below next to the line in the link below. Specifically, should there not be a filter_map=None right below this line? It seems that that this filter_map is always used in _fit but it is only set if validate is true. Maybe I am missing something.

https://github.com/Extreme-classification/siamesexml/blob/af053cf57cf3d5bbe3be6de4f7bd2e04ba589ecf/siamesexml/libs/model.py#L545

**Comment by drei34** [comment]
@kunaldahiya Am I wrong here?

**Comment by kunaldahiya** [comment]
Hi

Thanks for the suggestion - I agree that it should be set as None if validation is False. Please note that the filter file is used for the validation/test set only, i.e., it is used only when validation is set to True even in _fit.

**Comment by drei34** [comment]
@kunaldahiya Got it thanks. Just making explicit what I'm saying: if you set the config to FALSE then the code will crash if this line is not added. You never assign/compute filter_map unless validation is TRUE. So, this need to be set by default to None like validation_loader = None, otherwise the program crashes if validate=False since filter_map is passed down but it is never assigned ... I.e. I'm saying this is a (small) bug in the code for this case.

**Comment by kunaldahiya** [comment]
I see. Thanks a lot for clarifying! I have fixed it in the latest commit.
